services:
  postgres:
    image: postgres:16-alpine
    container_name: cartzone-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cartzone
      POSTGRES_USER: cartzone
      POSTGRES_PASSWORD: cartzone
    ports:
      - "5432:5432"
    volumes:
      - cartzone_pg_data:/var/lib/postgresql/data

volumes:
  cartzone_pg_data:
